name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get ver
        run: echo "$(cat v2ray.sh | grep ver=)" >> $GITHUB_ENV
      - name: zip
        run: zip -9vr code.zip . -x .\*
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: code.zip
          tag_name: ${{ env.is_sh_ver }}
